--con el usuario scinvgsf
grant select on SCINVGSF.t_concesionario to sretessf1;
grant select on SCINVGSF.t_concesionario to sretessf1  with grant option;
grant select on SCINVGSF.t_concesionario to sapregsf  with grant option;
grant references on SCINVGSF.t_concesionario to sretessf1 ;
--con el usuario SAPREGSF
grant select on SAPREGSF.SAPR_TIPODECLARACION to sretessf1;
grant references on SAPREGSF.SAPR_TIPODECLARACION to sretessf1;
--con el usuario sys
grant select on SAPREGSF.VW_REPRESENTANTE to sretessf1 ;


--CREAR VW_REPRESENTANTE VIEW EN SAPREGSF
SELECT R.NCODIGO, R.SNOMBRE, R.SAPEPAT, R.SAPEMAT, 
case when R.STIPODOC is null then '' else R.STIPODOC end STIPODOC, 
case when R.SNUMDOC is null then '' else R.SNUMDOC end SNUMDOC, 
case when R.SCARGO is null then '' else R.SCARGO end SCARGO,  
case when R.DFECINIPODER is null then '' else to_char(R.DFECINIPODER,'DD/MM/YYYY') end DFECINIPODER,  
T.CNC_ID
FROM SAPR_REPRESENTANTE R
INNER JOIN SAPR_USUARIO U
ON U.NCODIGO_USUARIO=R.NCODIGO_USUARIO
INNER JOIN SCINVGSF.T_CONCESIONARIO T
ON T.CNC_ID=U.COD_INSTITUCION
WHERE R.SESTADO='1'
AND U.SESTADO='1'
AND T.CNC_ESTADO='1'

  CREATE OR REPLACE FORCE  VIEW "VW_CREDITOREGISTRADO" ("NCODIGO", "SPERIODICIDAD_ORIGEN", "SRETRIBUCION_ORIGEN", "SANIOPERIODO_ORIGEN", "SMESPERIODO_ORIGEN", "SPERIODICIDAD_DESTINO", "SRETRIBUCION_DESTINO", "SANIOPERIODO_DESTINO", "SMESPERIODO_DESTINO", "DFECHAAPLICADO", "DFECHAMODIFICA", "DFECHAREGISTRO", "NIMPORTE", "NCODIGOCN", "NCODIGO_APORTE", "SUSUMODIFICA", "SUSUREGISTRA", "NCODIGO_ESTADO", "ESTADO") AS 
  SELECT  
NCODIGO,
(SELECT SDESCRIPCION FROM SRET_TIPOPERIODICIDAD P WHERE P.NCODIGO= NTIPO_PERIODICIDAD_ORIGEN)SPERIODICIDAD_ORIGEN,
(SELECT SDESCRIPCION FROM SRET_TIPORETRIBUCION P WHERE P.NCODIGO=NTIPO_RETRIBUCION_ORIGEN)SRETRIBUCION_ORIGEN,
SANIOPERIODO_ORIGEN,
SMESPERIODO_ORIGEN,
(SELECT SDESCRIPCION FROM SRET_TIPOPERIODICIDAD P WHERE P.NCODIGO=NTIPO_PERIODICIDAD_DESTINO)SPERIODICIDAD_DESTINO,
(SELECT SDESCRIPCION FROM SRET_TIPORETRIBUCION P WHERE P.NCODIGO=NTIPO_RETRIBUCION_DESTINO)SRETRIBUCION_DESTINO,
SANIOPERIODO_DESTINO,
SMESPERIODO_DESTINO,
DFECHAAPLICADO,
DFECHAMODIFICA,
DFECHAREGISTRO,
NIMPORTE,
NCODIGOCN,
NCODIGO_APORTE,
SUSUMODIFICA,
SUSUREGISTRA,
NCODIGO_ESTADO,
(SELECT SDESCRIPCION FROM SRET_ESTADO P WHERE P.NCODIGO =NCODIGO_ESTADO)ESTADO
  FROM SRET_CREDITO A;
--------------------------------------------------------
--  DDL for View VW_DECLARACION
--------------------------------------------------------

  CREATE OR REPLACE FORCE  VIEW "VW_DECLARACION" as
  SELECT NCODIGO,
      ID_CONCESIONARIO,
      ID_TIPOPERIODICIDAD,
      ID_TIPORETRIBUCION,
      SANIO_PERIODO,
      SMES_PERIODO,
      FECHA_VEN_PAGO,
      FECHA_VEN_PRES,
      SESTADO,
      
      ID_APORTETIPOPRESNT   
     ,NRET_RESULTANTE 
  FROM Sret_APORTE A

WHERE  A.NCODIGO=(
                SELECT MAX(B.NCODIGO) 
                FROM Sret_APORTE B 
                WHERE B.SMES_PERIODO=A.SMES_PERIODO 
                and  B.SANIO_PERIODO=A.SANIO_PERIODO  
               )      
AND A.ID_APORTETIPOPRESNT<>'I';
--------------------------------------------------------
--  DDL for View VW_NUEVOCREDITO
--------------------------------------------------------

  CREATE OR REPLACE FORCE  VIEW "VW_NUEVOCREDITO" AS 
  SELECT  
 rownum codigo,
 A.NCODIGO,
  A.ID_TIPOPERIODICIDAD ,
  A.ID_TIPORETRIBUCION ,
 (SELECT SDESCRIPCION FROM SRET_TIPOPERIODICIDAD WHERE NCODIGO=A.ID_TIPOPERIODICIDAD )STIPO_PERIODO_NOM,
 (SELECT SDESCRIPCION FROM SRET_TIPORETRIBUCION WHERE NCODIGO=A.ID_TIPORETRIBUCION )STIPO_RETRIBU_NOM,
  A.SANIO_PERIODO ,
  A.SMES_PERIODO ,
  a.NRET_RESULTANTE ,
  a.ID_CONCESIONARIO
  FROM VW_DECLARACION A 

  WHERE a.NRET_RESULTANTE<0
  and A.NCODIGO not in (SELECT C.NCODIGO_APORTE 
  FROM SRET_CREDITO C 
  where C.NCODIGO_APORTE!=-1 
  AND C.NCODIGO_ESTADO NOT in (0,3));--eliminado y anulado;
