insert into SRET_TIPO_DOCUMENTO(NCODIGO,s_nombre)values(SQ_RET_TIPODOCUMENTO.NEXTVAL,'D.N.I.');
insert into SRET_TIPO_DOCUMENTO(NCODIGO,s_nombre)values(SQ_RET_TIPODOCUMENTO.NEXTVAL,'R.U.C.');
insert into SRET_TIPO_DOCUMENTO(NCODIGO,s_nombre)values(SQ_RET_TIPODOCUMENTO.NEXTVAL,'CARNET DE EXTRANJERÍA');
commit;